version: "3.1"

services:
    db:
        image: flagstrips-db
        container_name: flagstrips-db
        restart: always
        build:
            context: ../database
        volumes:
            - ../database/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    adminer:
        image: adminer
        container_name: flagstrips-adminer
        restart: always
        ports:
            - 8080:8080
